### PR TITLE
Memory management changes and extra error checking

### PR DESCRIPTION
**Pull request by mikolalysenko**
There was a memory leak in the previous version, where if the LU decomposition failed L and U wouldn't get freed.

Also with the changes [here](https://github.com/substack/ndarray-crout-decomposition/pull/1), it should be possible to run the LU decomposition in place, thus saving a bit of memory.

In a few places it is possible to use ndscratch.malloc instead of ndscratch.zeros, thus avoiding unnecessary initialization.

I also added in X as a parameter so that if the system needs to be repeatedly solved then extra vectors won't get allocated.  A default vector is returned from the memory pool and so the user can free it if they want.

### CODE REVIEW

**Comment by ghost** [comment]
merged in 1.1.0

**Comment by ghost** [comment]
This actually broke all the tests.

**Comment by ghost** [comment]
Everything got really complicated and messy, I force-pushed over master from the 1.0.2 as 2.0.0 for now.

**Comment by ghost** [comment]
with some cherry-picking, merged in 2.1.0

**Comment by mikolalysenko** [comment]
Sorry about the mess.  I made the changes and sent the PR right before starting a long car ride.  I think I need to set up a global .gitignore to avoid fat fingering this stuff when I am in a hurry.

**Pull request closed without merging**
